export const LOGGED_IN = "LOGGED_IN";
export const NOT_LOGGED_IN = "NOT_LOGGED_IN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const BECOME_SITTER = "BECOME_SITTER";
export const NOT_BECOME_SITTER = "NOT_BECOME_SITTER";